# Site settings
# accessible in the templates via {{ site.myvariable }}.
title: Themes Hunt
description: >

baseurl: "" # the subpath of your site, e.g. /blog
url: https://themeshunt.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: binarymoon
github_username: binarymoon
permalink: /blog/:year/:title/
google_analytics: UA-55722-19
logo: /assets/images/favicon-192.png

# Build settings
markdown: kramdown

# SEO
twitter:
  username: binarymoon
#webmaster_verifications:
#  google: jpX5pDZ1_vsfHTm74TkvqTO5U5hjbpzsj6gnjuVeQXs

# Collections
collections:
  themes:
    output: true
    permalink: /wordpress-themes/:name/
  theme-roundups:
    output: true
    permalink: /:title/

# Default properties
defaults:
  - scope:
      type: pages
    values:
      image: /assets/images/og-image.jpg
      description: Hunting WordPress Themes
  - scope:
      type: themes
    values:
      layout: theme
      description: Hunting WordPress Themes
  - scope:
      type: theme-roundups
    values:
      layout: roundup
      description: Hunting WordPress Themes

gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - _pages
